name: fitnation_frontend
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.1
  flutter_hooks: ^0.13.0
  flutter_slidable: ^0.5.7
  freezed_annotation: ^0.12.0
  get_it: ^4.0.4
  implicitly_animated_reorderable_list: ^0.3.0
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  hexcolor: ^2.0.4
  auto_route: ^0.6.9
  http: ^0.12.2
  meta: ^1.2.4
  youtube_player_flutter: ^6.1.1
  
dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.2
  injectable_generator: ^1.0.4
  json_serializable: ^3.3.0
  lint: ^1.2.0


flutter:
  uses-material-design: true

  fonts:
    - family:  BottomNavIcons
      fonts:
        - asset: fonts/BottomNavIcons.ttf
    
